<a href="https://colab.research.google.com/github/3lonco/ColabNotebooks/blob/main/DeepLearningFromScratch2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# import Libraries

In [ ]:
#import
import numpy as np

# Concept of This Book

Experience of creating deep learning is a essentical key to understand deep learning profoundly.
The acknoldge and skills are required to understand DL deeply. This book present many experiment to generate DL from scratch. This process takes you a long time to finish it. Hoever, this progress includes many essential technicle which apprehend library and state of the art.


# Deep dive into natural language processsing
Simply, natural language processing is technich which enable computers to understand langaages we use. Computers cannot perceive our languages easily, thus NLP plays an important role in daily life. NLP has changed our lives dramatically, For example, web search engine makes us possible to find websites which we are looking for.
Like this, the technology which has given a huge impact on our life is based on the technique of NLP.

We focus on important technique of DL after learning NLP and processing time-sequence data. For instance, word2 vec, RNN, LSTM,GRU, seq2seq,and Attention. We explain these techniques with easily understanble words so that you can completly understand them by developing them from.

This book take you an adventure of NLP based on DL. This book is consist of the 8 chapters, which are designed to read in order. Many problems obstruct you, and you will need to overcome problems by improving proggramms. 

# Vector and Matrix


In [ ]:

# vector which has three components.
x = np.array([1,2,3])
x

array([1, 2, 3])

In [ ]:
# Matrix which has 2 row and 3 columns
W = np.array([[1,2,3],[4,5,6]])
W


array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
text = 'you say goodbye and I say hello.'
text = text.lower()
text

'you say goodbye and i say hello.'

In [8]:
text = text.replace('.',' .')
text

'you say goodbye and i say hello .'

In [10]:
words = text.split(' ')
words

['you', 'say', 'goodbye', 'and', 'i', 'say', 'hello', '.']

In [12]:
word_to_id = {}
id_to_word = {}
for word in words:
  print("for word in words:",word)
  if word not in word_to_id:
    new_id = len(word_to_id)
    word_to_id[word] = new_id
    id_to_word[new_id] = word

for word in words: you
for word in words: say
for word in words: goodbye
for word in words: and
for word in words: i
for word in words: say
for word in words: hello
for word in words: .


In [14]:
word_to_id

{'you': 0, 'say': 1, 'goodbye': 2, 'and': 3, 'i': 4, 'hello': 5, '.': 6}

In [15]:

id_to_word

{0: 'you', 1: 'say', 2: 'goodbye', 3: 'and', 4: 'i', 5: 'hello', 6: '.'}

In [17]:
corpus = [word_to_id[w] for w in words]
corpus

[0, 1, 2, 3, 4, 1, 5, 6]

In [19]:
corpus = np.array(corpus)
corpus

array([0, 1, 2, 3, 4, 1, 5, 6])

In [21]:
def preprocess(text):
  word_to_id = {}
  id_to_word = {}
  for word in words:
    if word not in word_to_id:
      new_id = len(word_to_id)
      word_to_id[word] = new_id
      id_to_word[new_id] = word
  corpus = np.array([word_to_id[w] for w in words])
  return corpus,word_to_id,id_to_word
text='you say goodbye and I say hello.'
corpus,word_to_id,id_to_word = preprocess(text)


for word in words: you
for word in words: say
for word in words: goodbye
for word in words: and
for word in words: i
for word in words: say
for word in words: hello
for word in words: .


In [23]:
import sys
sys.path.append('..')
import numpy as np
print(corpus)
print(id_to_word)

[0 1 2 3 4 1 5 6]
{0: 'you', 1: 'say', 2: 'goodbye', 3: 'and', 4: 'i', 5: 'hello', 6: '.'}


### 2.3.4共起行列

In [24]:
def create_co_matrix(corpus,vocab_size,window_size=1):
  corpus_size = len(corpus)
  co_matrix = np.zeros((vocab_size,vocab_size),dtype=np.int32)

  for idx, word_id in enumerate(corpus):
    for i in range(1,window_size+1):
      left_idx = idx - i 
      right_idx = idx + i

      if left_idx >= 0:
        left_word_id = corpus[left_idx]
        co_matrix[word_id,left_word_id] += 1
      
      if right_idx < corpus_size:
        right_word_id = corpus[right_idx]
        co_matrix[word_id,right_word_id] +=1

  return co_matrix

### 2.3.5ベクトル間の類似度


In [26]:
def cos_similarity(x,y,eps=1e-8):
  nx = x/ np.sqrt(np.sum(x**2))
  ny = y/ np.sqrt(np.sum(y**2))
  return np.dot(nx,ny)

text = 'you say goodbye and I say hello'
corpus,word_to_id,id_to_word=preprocess(text)
vocab_size=len(word_to_id)
C = create_co_matrix(corpus,vocab_size)

c0 = C[word_to_id['you']]
c1 = C[word_to_id['i']]
print(cos_similarity(c0,c1))

for word in words: you
for word in words: say
for word in words: goodbye
for word in words: and
for word in words: i
for word in words: say
for word in words: hello
for word in words: .
0.7071067811865475
