<a href="https://colab.research.google.com/github/3lonco/ColabNotebooks/blob/main/rapidchallenge_pca.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:

from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA #主成分分析器
import matplotlib.ticker as ticker
import numpy as np





In [7]:
data = np.array([[-1.0,-1.0],
                 [0.0,0.0],
                 [1.0,1.0]
                 ])

pca = PCA()
pca.fit(data)
feature =pca.transform(data)

In [6]:
feature

array([[-1.41421356,  0.        ],
       [ 0.        ,  0.        ],
       [ 1.41421356,  0.        ]])

In [9]:
pca.explained_variance_

array([2., 0.])

In [10]:
pca.explained_variance_ratio_

array([1., 0.])

In [11]:
pca.components_

(array([[ 0.70710678,  0.70710678],
        [-0.70710678,  0.70710678]]),)